language: php
sudo: false
php:
  - 5.5
  - 5.4
  - 5.6
  - 7.3
  - hhvm
env:
  global:
    - PLUGIN_NAME=EpsBankTransfer
    - REQUIRE=""
    - COVERALLS=1
  matrix:
    - CAKE_VERSION=2.5
    - CAKE_VERSION=2.6
    - CAKE_VERSION=2.10
before_script:
  - git clone https://github.com/hakito/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
script:
  - ../travis/script.sh
after_success:
  - ../travis/after_success.sh
